### ISSUE TITLE
Development 

### ISSUE THREAD

**Issue by s0urfruit** [kognise/neocel#1]
Hi, what ~~drugs~~ sorry, how tired were you when you made this? Seemed like you were really ~~high~~ tired.

**Comment by kognise** [comment]
yes uwu

**Comment by s0urfruit** [comment]
sir that's not an answer on how ~~high~~ tired you were

**Comment by kognise** [comment]
yes, fuck you

**Comment by s0urfruit** [comment]
not so professional, mrs mattick

**Comment by s0urfruit** [comment]
mr*

**Comment by ColomboJuan** [comment]
Are you okay?

**Comment by kognise** [comment]
this is for the memes

**Comment by s0urfruit** [comment]
> Are you okay?

No I am ~~high~~ tired, and so is @kognise
